settings:
  custom_fields:
    - label: NSO NED ID
      content_types:
       - dcim.device
      custom_field_choices:
        - value: NX-OS-nc-10.3
  bgp_peer_group_templates:
    - name: VXLAN-LEAF
      extra_attributes:
        remote_as: 65000
        update_source: lo0
    - name: VXLAN-SPINE
      extra_attributes:
        remote_as: 65000
        update_source: lo0